version: "3"

services:
  mongodb_fiverr:
    image: mongo:latest
    container_name: "tradegame_db"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=user"
      - "MONGO_INITDB_ROOT_PASSWORD=password123"
      - "MONGO_INITDB_DATABSE=tradegame_db"
    volumes:
      - .mongo-volume:/data/db
    ports:
      - 27017:27017
    command:
      - "--auth"
      - "--bind_ip=0.0.0.0"
